site_name: Knowhere Documentation
site_url: https://knowhere.live/docs
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details

site_dir: ../dist/docs
docs_dir: src/